version: 2

builds:
  - binary: runpodctl
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    flags: [-mod=mod]
    ldflags:
      - -s -w -X main.Version={{ .Version }}-{{ .ShortCommit }}

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: runpodctl
    homepage: "https://github.com/runpod/runpodctl"
    repository:
      owner: runpod
      name: homebrew-runpodctl
    commit_author:
      name: runpod
      email: support@runpod.io

checksum:
  name_template: "checksums.txt"
