version: 2

builds:
  - id: default
    binary: runpodctl
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    flags: [-mod=mod]
    ldflags:
      - -s -w -X main.Version={{ .Version }}-{{ .ShortCommit }}

  - id: linux_amd64_upx
    binary: runpodctl
    goos: [linux]
    goarch: [amd64]
    env: [CGO_ENABLED=0]
    flags: [-mod=mod]
    ldflags:
      - -s -w -X main.Version={{ .Version }}-{{ .ShortCommit }}

upx:
  - enabled: true
    ids: [linux_amd64_upx]
    goos: [linux]
    goarch: [amd64]
    lzma: false
    compress: best

universal_binaries:
  - id: default
    replace: true

archives:
  - id: default
    ids: [default]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

  # UPX linux/amd64 artifact, also archived for internal Runpod use
  - id: upx
    ids: [linux_amd64_upx]
    formats: [tar.gz]
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}-upx"

release:
  prerelease: auto

homebrew_casks:
  - name: runpodctl
    homepage: "https://github.com/runpod/runpodctl"
    repository:
      owner: runpod
      name: homebrew-runpodctl
    commit_author:
      name: runpod
      email: support@runpod.io
    ids: [default]

checksum:
  name_template: "checksums_{{ .Version }}_sha256.txt"
  algorithm: sha256
